#lang ivy1.7

type addr_t
type data_t
type nid_t

type idx_t
type midx_t
type txn_idx_t
individual txn_idx_null: txn_idx_t

type nat_idx_t
interpret nat_idx_t -> nat

type cache_state_t = {cs_i, cs_uc, cs_ud, cs_sc}

individual hn_nid: nid_t
individual sn_nid: nid_t
axiom hn_nid ~= sn_nid

derived is_rn(N: nid_t) = N ~= hn_nid & N ~= sn_nid
derived is_hn(N: nid_t) = N = hn_nid
derived is_sn(N: nid_t) = N = sn_nid
