#lang ivy1.7

type addr_t
type data_t
type nid_t

type index_t
interpret index_t -> int

type cache_state_t = {cs_i, cs_uc, cs_ud, cs_sc}

individual hn_nid: nid_t
individual sn_nid: nid_t
axiom hn_nid ~= sn_nid

function is_rn(N: nid_t): bool
definition is_rn(N: nid_t) = N ~= hn_nid & N ~= sn_nid

function is_hn(N: nid_t): bool
definition is_hn(N: nid_t) = N = hn_nid

function is_sn(N: nid_t): bool
definition is_sn(N: nid_t) = N = sn_nid
