#lang ivy1.7

type idx_t

relation in_use(I: idx_t)

after init {
    in_use(I) := false;
}

export action new returns(res: idx_t) = {
    # require ~in_use(res);
    # in_use(res) := true;
    if some (f: idx_t) ~in_use(f) {
        in_use(f) := true;
        res := f;
    } else {
        assert false;
    }
}

export action delete(res: idx_t) = {
    require in_use(res);
    in_use(res) := false;
    # if some (f: idx_t) ~in_use(f) {
    #     in_use(f) := true;
    #     res := f;
    # } else {
    #     assert false;
    # }
}

attribute method = bmc[10]
