#lang ivy1.8

type idx_t

relation in_use(I: idx_t)

after init {
    in_use(I) := false;
}

action new(res: idx_t) = {
    require ~in_use(res);
    in_use(res) := true;
}

export action ttt(res: idx_t) = {
    # require ~in_use(res);
    # in_use(res) := true;
    call new(res);
}

export action delete(res: idx_t) = {
    require in_use(res);
    in_use(res) := false;
}

attribute method = bmc[10]
